services:
  - type: web
    name: affine_selfhosted
    runtime: image
    image:
      url: ghcr.io/toeverything/affine-graphql:canary
    region: ohio
    plan: free
    # preDeployCommand: cat /etc/secrets/affine.env.js
    # disk:
    #   name: custom_configurations
    #   mountPath: /root/.affine/
    #   sizeGB: 10
    envVars:
      - key: NODE_OPTIONS
        value: "--import=./scripts/register.js"
      # - key: AFFINE_CONFIG_PATH
      #   value: /etc/secrets/
      #
      - key: REDIS_SERVER_HOST
        fromService:
          type: redis
          name: affine_redis
          property: host
      - key: REDIS_SERVER_PORT
        fromService:
          type: redis
          name: affine_redis
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: affine_postgres
          property: connectionString
      # - key: SERVER_FLAVOR
      #   value: selfhosted
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        sync: false
      - key: AFFINE_SERVER_HOST
        sync: false
      - key: AFFINE_SERVER_PORT
        value: 3010
      - key: PORT
        fromService:
          name: affine_selfhosted
          type: web
          envVarKey: AFFINE_SERVER_PORT
      - key: AFFINE_ADMIN_EMAIL
        sync: false
      - key: AFFINE_ADMIN_PASSWORD
        sync: false
      # Telemetry allows us to collect data on how you use the affine. This data will helps us improve the app and provide better features.
      # Uncomment next line if you wish to quit telemetry.
      - key: TELEMETRY_ENABLE
        value: "false"
      - key: MAILER_HOST
        value: smtp.gmail.com
      - key: MAILER_PORT
        value: 587
      - key: MAILER_USER
        sync: false
      - key: MAILER_PASSWORD
        sync: false
  - type: redis
    name: affine_redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    region: ohio
    plan: free
    maxmemoryPolicy: allkeys-lru
databases:
  - name: affine_postgres
    # postgresMajorVersion:
    region: ohio
    plan: free
    databaseName: affine
    user: affine
